# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: JOEL ABRAHAM PLUAS
title: MI PRIMER BLOG
email: ellokp2001@gmail.com
phone: 0943555698
#website: mjfortaleza00@gmail.com

# Social links
twitter_username: JoelPluas4
github_username:  JoelPluas4
#dribbble_username: jekyll
facebook_username: Moises.david.019
#flickr_username: jekyll
instagram_username: _david_o_n
#linkedin_username: david-ochoa-85066a199
#xing_username: jekyll
#pinterest_username: jekyll
youtube_username: JoelPluas4
#googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: Directory of profile image (eg. images/profile.jpeg)
about_content: | # this will include new lines to allow paragraphs
  Buenos dias, a todos si desean mas informacion aqui esta el link sobre mi biografia [links](https://moises2018-gif.github.io/word/) and highlight things <mark>like this</mark>.


# Projects Section
# projects_title: Projects #(Use this to override about projects section title)


# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  Lo que me impulsa a seguir adelante con mi desarrollo son mis padres ya que ellos me han dado el apoyo desde siempre, por otro lado, es mi maestro de lenguaje ya que él ha estado diciéndonos que investiguemos, que leamos. Por tercero estoy yo ya que si no avanzo y no me paro firme la vida me golpeara más fuerte de lo normal..

  

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
